### PR TITLE
WFCORE-6407 Deprecate non-default contructors from AbstractAddStepHandler and AbstractWriteAttributeHandler

### PR DESCRIPTION
**Pull request by pferraro**
https://issues.redhat.com/browse/WFCORE-6407

Essentially, this change avoids the need for subsystems to specify AttributeDefinition instances to their add resource and write-attribute operation handlers.
See jira for full rationale.
This change will require minor unit test updates to wildfly, so expect failures in full integration test runs until those fixes are available and merged.
Given that this proposed change affects every add/write-attribute operation, I wanted to make this available for review/feedback as soon as possible.

This should simplify the creation and registration of add and write-attribute operation handlers as well as further reduce our memory footprint, since many operation handler implementations can now be consolidated both within and across subsystems.

~~Requires https://github.com/wildfly/wildfly-core/pull/5644~~ Merged.

### CODE REVIEW

**Comment by pferraro** [comment]
Added hold label until I sort out some missing domain testsuite changes.

**Comment by pferraro** [comment]
Full-integration tests failures are addressed by https://github.com/wildfly/wildfly/pull/17007

**Review by yersan — COMMENTED** [review]
@pferraro , it looks like there are compilation errors combining the WildFly counterpart with this PR:

https://ci.wildfly.org/buildConfiguration/WF_WildFlyCoreIntegrationExperiments/380109?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

```
16:40:39] :	 [Step 4/5] [INFO] 100 warnings 
[16:40:39] :	 [Step 4/5] [INFO] -------------------------------------------------------------
[16:40:39] :	 [Step 4/5] [INFO] -------------------------------------------------------------
[16:40:39]W:	 [Step 4/5] [ERROR] COMPILATION ERROR : 
[16:40:39] :	 [Step 4/5] [INFO] -------------------------------------------------------------
[16:40:39]W:	 [Step 4/5] [ERROR] /opt/buildAgent/work/5732051f49542de7/full/ee/src/main/java/org/jboss/as/ee/subsystem/GlobalDirectoryResourceDefinition.java:[76,61] ReloadRequiredRemoveStepHandler() has protected access in org.jboss.as.controller.ReloadRequiredRemoveStepHandler
[16:40:39] :	 [Step 4/5] [INFO] 1 error
[16:40:39] :	 [Step 4/5] [INFO] -------------------------------------------------------------
[16:40:39] :	 [Step 4/5] [Maven Watcher] 
[16:40:39]E:	 [Step 4/5] Compiler
```

Ideally, we should have the commit squashed or at least have the Jira issue number on each commit.

File: remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointResource.java [hunk 1]
```diff
@@ -54,14 +56,18 @@ class RemotingEndpointResource extends SimpleResourceDefinition {
     static {
         Map<String, AttributeDefinition> attrs = new LinkedHashMap<>();
         assert RemotingSubsystemRootResource.WORKER.getName().equals(RemotingSubsystemRootResource.WORKER.getXmlName());
-        attrs.put(RemotingSubsystemRootResource.WORKER.getName(), RemotingSubsystemRootResource.WORKER);
-        for (AttributeDefinition ad : RemotingSubsystemRootResource.OPTIONS) {
+        attrs.put(RemotingSubsystemRootResource.WORKER.getName(), alias(RemotingSubsystemRootResource.WORKER));
```
[the remark this answers is not in the document]
Comment (pferraro) [reply remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointResource.java:59]: > @pferraro , it looks like there are compilation errors combining the WildFly counterpart with this PR:
> 
> https://ci.wildfly.org/buildConfiguration/WF_WildFlyCoreIntegrationExperiments/380109?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

Blech.  Restricting the visibility of this constructor was meant to be temporary - to detect cases that should be using the static INSTANCE instead.
The intention is to @Deprecate the public constructor.  I'll add the HOLD label while I clean this up.

[the remark this answers is not in the document]
Comment (pferraro) [reply remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointResource.java:59]: > Why is the alias created here and not handled directly on the `RemotingSubsystemRootResource.WORKER` with `.addFlag(AttributeAccess.Flag.ALIAS)` ?

I don't know the full history of this subsystem, but according to the existing code, the WORKER attribute of the /subsystem=remoting resource is not an alias, while all of the attributes of the /subsystem=remoting/configuration=endpoint resource are aliases referencing the parent.

[the remark this answers is not in the document]
Comment (pferraro) [reply remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingEndpointResource.java:59]: > Ideally, we should have the commit squashed or at least have the Jira issue number on each commit.

I don't generally add the jira issue number to a commit if the change is not directly related the commit and can be a source of confusion.

**Comment by pferraro** [comment]
Rebasing against main.

**Comment by pferraro** [comment]
Rebased against main for hopefully the final time.  All dependent changes on which this branch was based have been merged.
@bstansberry I think you might be the only person who can reasonably review this.

File: remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemRootResource.java [hunk 2]
```diff
@@ -227,10 +226,8 @@ private Attributes(ProcessType processType, boolean forDomain) {
                             .build();
                 }
             } else if (forDomain) {
-                this.worker = SimpleAttributeDefinitionBuilder.create(WORKER).setCapabilityReference((CapabilityReferenceRecorder) null).build();
```
Comment (bstansberry) [inline remoting/subsystem/src/main/java/org/jboss/as/remoting/RemotingSubsystemRootResource.java:230]: @pferraro Fyi re https://issues.redhat.com/browse/WFCORE-6473 and https://issues.redhat.com/browse/WFCORE-6472

File: remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java [hunk 3]
```diff
@@ -178,12 +178,6 @@ public void testSubsystemWithConnectorProperties() throws Exception {
         for (AttributeDefinition ad : RemotingSubsystemRootResource.LEGACY_ATTRIBUTES) {
             assertFalse(ad.getName(), subsystem.hasDefined(ad.getName()));
         }
-        ModelNode endpoint = subsystem.get(RemotingEndpointResource.ENDPOINT_PATH.getKey(), RemotingEndpointResource.ENDPOINT_PATH.getValue());
-        for (AttributeDefinition ad : RemotingEndpointResource.ATTRIBUTES.values()) {
-            ModelNode dflt = ad.getDefaultValue();
-            assertEquals(ad.getName(), dflt == null ? new ModelNode() : dflt, endpoint.require(ad.getName()));
-        }
```
Comment (bstansberry) [inline remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java:185]: Note to self: This needs to be removed because changing to aliases means the values no longer show up in a read-resource.

Comment (bstansberry) [reply remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java:185]: @pferraro is this commit absolutely required for this work?

This Flag.ALIAS addition results in the attributes not appearing in a normal read-resource, which makes the resource basically pointless, as it only exists for compatibility reasons. And it is pointless anyway, and is deprecated. But really we should have removed it in 29 Alpha1 and probably should now (and port that downstream.)

IOW if we must break it we should probably break it all the way and port that downstream. That's a bigger task though. @darranl FYI.

**Comment by bstansberry** [comment]
@pferraro Other than my concern about the remoting endpoint alias thing this all LGTM. And that need not block this while I'm away, so long as there's a discussion/decision about what to do with that resource here and downstream. Basically...

1) If we're going to remove the resource, what you did here is fine; we'll just follow it up with the removal later in WF 30 work.
2) If we're going to keep the resource, but what you did here is with the alias flag required for your overall work, then fine. It's a correct change and we need to move forward.
3) If we're going to keep the resource but what you did with the alias flag is not required, then lets not do it and come back to it later.

File: remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java (hunk 3 above)
Comment (pferraro) [reply remoting/tests/src/test/java/org/jboss/as/remoting/RemotingLegacySubsystemTestCase.java:185]: > @pferraro is this commit absolutely required for this work?

Yes.  The current /subsystem=remoting/configuration=endpoint resource has 2 fundamental issues:

- The runtime behavior of its attributes do not comply with their management description.
- The worker attribute definition is not consistent between domain vs server wrt capability references - which, once the correct attribute definition flags are applied, otherwise breaks galleon.

WFCORE-6407 ensures that the parameters of the OperationDefinition for the add operation of a given resource are consistent with the parameters used the OperationStepHandler handling the add operation.  Without this commit, add operation parameters as generated by https://github.com/pferraro/wildfly-core/blob/WFCORE-6407/controller/src/main/java/org/jboss/as/controller/SimpleResourceDefinition.java#L245 will not be correct, and lots of model compatibility tests will fail.

> This Flag.ALIAS addition results in the attributes not appearing in a normal read-resource, which makes the resource basically pointless, as it only exists for compatibility reasons.

Presumably, retaining compatibility is not pointless, unless this deprecation is sufficiently old.

> But really we should have removed it in 29 Alpha1 and probably should now (and port that downstream.)

If this child resource can be removed, all the better.

**Comment by pferraro** [comment]
Adding hold label.  This will be rebased on WFCORE-6472/WFCORE-6473 work.

**Comment by pferraro** [comment]
> @pferraro Other than my concern about the remoting endpoint alias thing this all LGTM. And that need not block this while I'm away, so long as there's a discussion/decision about what to do with that resource here and downstream. Basically...
> 
> 1. If we're going to remove the resource, what you did here is fine; we'll just follow it up with the removal later in WF 30 work.
> 2. If we're going to keep the resource, but what you did here is with the alias flag required for your overall work, then fine. It's a correct change and we need to move forward.
> 3. If we're going to keep the resource but what you did with the alias flag is not required, then lets not do it and come back to it later.

Provided that https://github.com/wildfly/wildfly-core/pull/5643 looks ok, I will rebase this branch on top of that work.

**Comment by pferraro** [comment]
Rebased on top of https://github.com/wildfly/wildfly-core/pull/5644

**Comment by pferraro** [comment]
Rebased against main.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
Thanks @pferraro
